(function () {
  const categories = [
    {
      id: "penzugyi",
      title: "Pénzügyi kalkulátorok",
      shortTitle: "Pénzügyi",
      url: "penzugyi.html",
      description:
        "Befektetés, hitel, infláció, osztalék és fizetéssel kapcsolatos számítások.",
      seo:
        "Pénzügyi kalkulátorainkkal gyorsan kiszámolhatod a hitelek, befektetések, infláció, osztalék és számlázási határidők legfontosabb értékeit.",
      cardClass: "card-finance",
    },
    {
      id: "epitoipari",
      title: "Építőipari kalkulátorok",
      shortTitle: "Építőipari",
      url: "epitoipari.html",
      description:
        "Beton, csempe, festék és tégla mennyiségének tervezése felújításhoz.",
      seo:
        "Építőipari kalkulátoraink segítenek megbecsülni a felújításhoz vagy építkezéshez szükséges alapanyagok mennyiségét.",
      cardClass: "card-building",
    },
    {
      id: "egeszseg",
      title: "Egészség kalkulátorok",
      shortTitle: "Egészség",
      url: "egeszseg.html",
      description:
        "BMI és kalóriaszükséglet számítás az egészségtudatos mindennapokhoz.",
      seo:
        "Egészség kalkulátoraink gyors tájékoztatást adnak testtömegindexről, napi kalóriaszükségletről és alapvető egészségügyi mutatókról.",
      cardClass: "card-health",
    },
    {
      id: "mindennapi",
      title: "Mindennapi kalkulátorok",
      shortTitle: "Mindennapi",
      url: "mindennapi.html",
      description:
        "Százalék, ÁFA és gyakori hétköznapi számítások egyszerűen.",
      seo:
        "Mindennapi kalkulátoraink a gyors százalékszámításhoz, ÁFA számításhoz és gyakori hétköznapi pénzügyi műveletekhez adnak segítséget.",
      cardClass: "card-general",
    },
    {
      id: "auto",
      title: "Autós kalkulátorok",
      shortTitle: "Autó",
      url: "auto.html",
      description:
        "Fogyasztás, utazási költség és autózással kapcsolatos számítások.",
      seo:
        "Autós kalkulátorainkkal gyorsan megbecsülheted az utazási költségeket, fogyasztást és az autóhasználathoz kapcsolódó kiadásokat.",
      cardClass: "card-auto",
    },
    {
      id: "atvaltok",
      title: "Átváltók",
      shortTitle: "Átváltók",
      url: "atvaltok.html",
      description:
        "Mértékegységek, adatmennyiségek, sebesség, idő és deviza átváltása.",
      seo:
        "Átváltóinkkal hosszúságot, tömeget, területet, térfogatot, időt, sebességet, adatmennyiséget, hőmérsékletet és devizát válthatsz át.",
      cardClass: "card-general",
    },
  ];

  const calculators = [
    {
      title: "Nettó - bruttó kalkulátor",
      url: "kalkulatorok/netto-brutto-kalkulator.html",
      category: "penzugyi",
      description: "Fizetés nettó vagy bruttó összegének kiszámítása.",
      keywords: "fizetés bér adó járulék nettó bruttó",
      popular: true,
    },
    {
      title: "Hitel törlesztő kalkulátor",
      url: "kalkulatorok/hitel-torleszto-kalkulator.html",
      category: "penzugyi",
      description: "Havi törlesztőrészlet számítása hitelösszeg és futamidő alapján.",
      keywords: "lakáshitel személyi kölcsön kamat törlesztés",
    },
    {
      title: "Hitelképesség kalkulátor",
      url: "kalkulatorok/hitelkepesseg-kalkulator.html",
      category: "penzugyi",
      description: "Becsüld meg, mekkora hitel férhet bele a jövedelmedbe.",
      keywords: "jtm hitel jövedelem bank önerő",
    },
    {
      title: "Lakáshitel önerő kalkulátor",
      url: "kalkulatorok/lakas-hitel-onero-kalkulator.html",
      category: "penzugyi",
      description: "Szükséges önerő kiszámítása lakásvásárláshoz.",
      keywords: "lakás ingatlan önerő lakáshitel",
    },
    {
      title: "Osztalék kalkulátor",
      url: "kalkulatorok/osztalek-kalkulator.html",
      category: "penzugyi",
      description: "Osztalék és várható passzív jövedelem számítása.",
      keywords: "részvény hozam passzív jövedelem",
      popular: true,
    },
    {
      title: "ETF kalkulátor",
      url: "kalkulatorok/etf-kalkulator.html",
      category: "penzugyi",
      description: "ETF befektetés várható növekedésének becslése.",
      keywords: "befektetés tőzsde hozam rendszeres megtakarítás",
      popular: true,
    },
    {
      title: "Mikor leszek milliomos?",
      url: "kalkulatorok/milliomos-kalkulator.html",
      category: "penzugyi",
      description: "Számold ki, mennyi idő kell a célösszeg eléréséhez.",
      keywords: "megtakarítás vagyon célösszeg pénzügyi cél",
    },
    {
      title: "Infláció kalkulátor",
      url: "kalkulatorok/inflacio-kalkulator.html",
      category: "penzugyi",
      description: "Pénz vásárlóerejének változása infláció mellett.",
      keywords: "infláció pénzromlás árak vásárlóerő",
    },
    {
      title: "Kamatos kamat kalkulátor",
      url: "kalkulatorok/kamatos-kamat-kalkulator.html",
      category: "penzugyi",
      description: "Befektetés növekedése kamatos kamattal.",
      keywords: "kamat megtakarítás befektetés hozam",
    },
    {
      title: "Havi költségvetés kalkulátor",
      url: "kalkulatorok/havi-koltsegvetes-kalkulator.html",
      category: "penzugyi",
      description: "Tervezd meg a havi bevételeidet, kiadásaidat és megtakarítási arányodat.",
      keywords: "költségvetés bevétel kiadás megtakarítás havi pénzügyi tervezés",
    },
    {
      title: "Fizetési határidő kalkulátor",
      url: "kalkulatorok/fizetesi-hatarido-kalkulator.html",
      category: "penzugyi",
      description: "Fizetési határidő kiszámítása számlázáshoz.",
      keywords: "számla fizetési határidő vállalkozás",
      popular: true,
    },
    {
      title: "Számla teljesítés kalkulátor",
      url: "kalkulatorok/szamla-teljesites-kalkulator.html",
      category: "penzugyi",
      description: "Számla teljesítési dátumának kiszámítása.",
      keywords: "számlázás teljesítés dátum vállalkozás",
      popular: true,
    },
    {
      title: "Beton kalkulátor",
      url: "kalkulatorok/beton-kalkulator.html",
      category: "epitoipari",
      description: "Szükséges beton mennyiségének kiszámítása.",
      keywords: "beton alap köbméter építkezés",
    },
    {
      title: "Csempe kalkulátor",
      url: "kalkulatorok/csempe-kalkulator.html",
      category: "epitoipari",
      description: "Csempe mennyiség kiszámítása burkoláshoz.",
      keywords: "csempe burkolat járólap négyzetméter",
    },
    {
      title: "Festék kalkulátor",
      url: "kalkulatorok/festek-kalkulator.html",
      category: "epitoipari",
      description: "Festékmennyiség becslése falakhoz és felületekhez.",
      keywords: "festés festék liter fal",
    },
    {
      title: "Tégla kalkulátor",
      url: "kalkulatorok/tegla-kalkulator.html",
      category: "epitoipari",
      description: "Tégla mennyiség kiszámítása falazáshoz.",
      keywords: "tégla falazat építkezés darab",
    },
    {
      title: "BMI kalkulátor",
      url: "kalkulatorok/bmi-kalkulator.html",
      category: "egeszseg",
      description: "Testtömegindex kiszámítása testsúly és magasság alapján.",
      keywords: "testtömeg index egészség súly magasság",
    },
    {
      title: "Kalória kalkulátor",
      url: "kalkulatorok/kaloria-kalkulator.html",
      category: "egeszseg",
      description: "Napi kalóriaszükséglet becslése.",
      keywords: "kalória étrend fogyás tömegnövelés",
    },
    {
      title: "Százalék kalkulátor",
      url: "kalkulatorok/szazalek-kalkulator.html",
      category: "mindennapi",
      description: "Gyors százalékszámítás hétköznapi helyzetekhez.",
      keywords: "százalék kedvezmény arány növekedés csökkenés",
    },
    {
      title: "ÁFA kalkulátor",
      url: "kalkulatorok/afa-kalkulator.html",
      category: "mindennapi",
      description: "ÁFA hozzáadása vagy levonása nettó és bruttó értékből.",
      keywords: "áfa nettó bruttó adó számla",
    },
    {
      title: "Autós kalkulátor",
      url: "kalkulatorok/auto-kalkulator.html",
      category: "auto",
      description: "Utazási és autós költségek kiszámítása.",
      keywords: "fogyasztás üzemanyag utazás benzin dízel",
      popular: true,
    },
    {
      title: "Hőmérséklet átváltó",
      url: "kalkulatorok/homerseklet-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Celsius, Fahrenheit és Kelvin átváltása.",
      keywords: "celsius fahrenheit kelvin hőfok",
    },
    {
      title: "Hosszúság átváltó",
      url: "kalkulatorok/hosszusag-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Milliméter, centiméter, méter, kilométer, inch és mérföld.",
      keywords: "hossz méter inch mérföld",
    },
    {
      title: "Tömeg átváltó",
      url: "kalkulatorok/tomeg-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Gramm, kilogramm, tonna, font és uncia átváltása.",
      keywords: "súly tömeg kg font uncia",
    },
    {
      title: "Terület átváltó",
      url: "kalkulatorok/terulet-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Négyzetméter, hektár és négyzetkilométer átváltása.",
      keywords: "terület négyzetméter hektár",
    },
    {
      title: "Térfogat átváltó",
      url: "kalkulatorok/terfogat-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Milliliter, liter, köbméter és gallon átváltása.",
      keywords: "térfogat liter gallon köbméter",
    },
    {
      title: "Idő átváltó",
      url: "kalkulatorok/ido-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Másodperc, perc, óra, nap és hét átváltása.",
      keywords: "idő óra perc nap hét",
    },
    {
      title: "Sebesség átváltó",
      url: "kalkulatorok/sebesseg-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Km/h, mph és m/s közötti átváltás.",
      keywords: "sebesség kmh mph ms",
    },
    {
      title: "Adatmennyiség átváltó",
      url: "kalkulatorok/adatmeret-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "KB, MB, GB és TB átváltása.",
      keywords: "adat tárhely méret byte",
    },
    {
      title: "Deviza átváltó",
      url: "kalkulatorok/deviza-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Forint, euró, dollár, font és más pénznemek átváltása.",
      keywords: "deviza valuta euró dollár forint",
    },
    {
      title: "Padlóburkolat kalkulátor",
      url: "kalkulatorok/padlo-burkolat-kalkulator.html",
      category: "epitoipari",
      description: "Számold ki a szükséges laminált padló, parketta vagy burkolat mennyiségét.",
      keywords: "padló burkolat laminált parketta alapterület veszteség",
    },
    {
      title: "Gipszkarton kalkulátor",
      url: "kalkulatorok/gipszkarton-kalkulator.html",
      category: "epitoipari",
      description: "Becsüld meg, hány gipszkarton lapra lesz szükséged falhoz vagy mennyezethez.",
      keywords: "gipszkarton lap fal mennyezet építés",
    },
    {
      title: "Tapéta kalkulátor",
      url: "kalkulatorok/tapeta-kalkulator.html",
      category: "epitoipari",
      description: "Számold ki, hány tekercs tapétára lehet szükség egy helyiségben.",
      keywords: "tapéta tekercs fal lakásfelújítás",
    },
    {
      title: "Vakolat kalkulátor",
      url: "kalkulatorok/vakolat-kalkulator.html",
      category: "epitoipari",
      description: "Becsüld meg a vakolat vagy glettanyag mennyiségét felület és rétegvastagság alapján.",
      keywords: "vakolat glett anyag fal vastagság",
    },
    {
      title: "Hőszigetelés kalkulátor",
      url: "kalkulatorok/hoszigeteles-kalkulator.html",
      category: "epitoipari",
      description: "Tervezd meg a homlokzati vagy födémszigetelés lapmennyiségét.",
      keywords: "hőszigetelés homlokzat eps xps kőzetgyapot",
    },
    {
      title: "Térkövezés kalkulátor",
      url: "kalkulatorok/terkovezes-kalkulator.html",
      category: "epitoipari",
      description: "Számold ki térkő, szegélykő és ráhagyás becsült mennyiségét.",
      keywords: "térkő udvar járda kert térkövezés",
    },
    {
      title: "Tetőcserép kalkulátor",
      url: "kalkulatorok/tetocserep-kalkulator.html",
      category: "epitoipari",
      description: "Becsüld meg a tetőfedéshez szükséges cserepek számát.",
      keywords: "tető cserép tetőfedés építkezés",
    },
    {
      title: "Fuga kalkulátor",
      url: "kalkulatorok/fuga-kalkulator.html",
      category: "epitoipari",
      description: "Számold ki a várható fugázóanyag-szükségletet burkoláshoz.",
      keywords: "fuga burkolás csempe járólap fugázó",
    },
    {
      title: "Vízfogyasztás kalkulátor",
      url: "kalkulatorok/vizfogyasztas-kalkulator.html",
      category: "egeszseg",
      description: "Becsüld meg a napi ajánlott folyadékbevitelt testsúly és aktivitás alapján.",
      keywords: "vízfogyasztás folyadék testsúly hidratálás",
    },
    {
      title: "Pulzus zóna kalkulátor",
      url: "kalkulatorok/pulzus-zona-kalkulator.html",
      category: "egeszseg",
      description: "Számold ki az edzéshez használható pulzustartományokat.",
      keywords: "pulzus edzés kardió zóna sport",
    },
    {
      title: "Terhességi kalkulátor",
      url: "kalkulatorok/terhessegi-kalkulator.html",
      category: "egeszseg",
      description: "Számold ki a várható szülési dátumot az utolsó menstruáció alapján.",
      keywords: "terhesség szülés dátum kalkulátor",
    },
    {
      title: "Ideális testsúly kalkulátor",
      url: "kalkulatorok/idealis-testsuly-kalkulator.html",
      category: "egeszseg",
      description: "Becsüld meg az ideális testsúlyt magasság és nem alapján.",
      keywords: "ideális testsúly magasság egészség",
    },
    {
      title: "Testzsír százalék kalkulátor",
      url: "kalkulatorok/testzsir-kalkulator.html",
      category: "egeszseg",
      description: "Becsüld meg a testzsírszázalékot derék, nyak, csípő és magasság alapján.",
      keywords: "testzsír százalék derék csípő egészség",
    },
    {
      title: "Makró kalkulátor",
      url: "kalkulatorok/makro-kalkulator.html",
      category: "egeszseg",
      description: "Oszd fel a napi kalóriát fehérje, szénhidrát és zsír között.",
      keywords: "makró fehérje szénhidrát zsír étrend",
    },
    {
      title: "Alvásciklus kalkulátor",
      url: "kalkulatorok/alvasciklus-kalkulator.html",
      category: "egeszseg",
      description: "Tervezd meg, mikor érdemes lefeküdni vagy felkelni 90 perces ciklusokkal.",
      keywords: "alvás ciklus lefekvés felkelés",
    },
    {
      title: "BMR kalkulátor",
      url: "kalkulatorok/bmr-kalkulator.html",
      category: "egeszseg",
      description: "Számold ki az alapanyagcserédet Mifflin-St Jeor képlettel.",
      keywords: "bmr alapanyagcsere kalória",
    },
    {
      title: "Derék-csípő arány kalkulátor",
      url: "kalkulatorok/derek-csipo-kalkulator.html",
      category: "egeszseg",
      description: "Számold ki a derék-csípő arányt, egy egyszerű egészségi mutatót.",
      keywords: "derék csípő arány whr",
    },
    {
      title: "Fehérje szükséglet kalkulátor",
      url: "kalkulatorok/feherje-szukseglet-kalkulator.html",
      category: "egeszseg",
      description: "Becsüld meg a napi fehérjeigényt testsúly és cél alapján.",
      keywords: "fehérje protein edzés fogyás",
    },
    {
      title: "Árkedvezmény kalkulátor",
      url: "kalkulatorok/ar-kedvezmeny-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki az akciós árat, kedvezményt és megtakarítást.",
      keywords: "kedvezmény akció ár százalék",
    },
    {
      title: "Borravaló kalkulátor",
      url: "kalkulatorok/borravalo-kalkulator.html",
      category: "mindennapi",
      description: "Oszd el a számlát és számold ki a borravalót több főre.",
      keywords: "borravaló számla étterem",
    },
    {
      title: "Munkaidő kalkulátor",
      url: "kalkulatorok/munkaido-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki a heti és havi munkaórát napi óraszám alapján.",
      keywords: "munkaidő óra hét hónap",
    },
    {
      title: "Életkor kalkulátor",
      url: "kalkulatorok/eletkor-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki az életkort években, hónapokban és napokban.",
      keywords: "életkor születésnap dátum",
    },
    {
      title: "Dátum különbség kalkulátor",
      url: "kalkulatorok/datum-kulonbseg-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki két dátum közötti napok számát egyszerűen.",
      keywords: "dátum különbség napok",
    },
    {
      title: "Átlag kalkulátor",
      url: "kalkulatorok/atlag-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki több érték átlagát darabszám és összeg alapján.",
      keywords: "átlag számítás összeg darab",
    },
    {
      title: "Egységár kalkulátor",
      url: "kalkulatorok/egysegar-kalkulator.html",
      category: "mindennapi",
      description: "Hasonlítsd össze termékek egységárát kiszerelés alapján.",
      keywords: "egységár ár kiszerelés vásárlás",
    },
    {
      title: "Rezsi megosztás kalkulátor",
      url: "kalkulatorok/rezsi-megosztas-kalkulator.html",
      category: "mindennapi",
      description: "Oszd szét a közös költségeket lakótársak vagy családtagok között.",
      keywords: "rezsi megosztás lakótárs közös költség",
    },
    {
      title: "Órabér kalkulátor",
      url: "kalkulatorok/oraber-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki az órabéred havi bér és munkaóra alapján.",
      keywords: "órabér fizetés munkaóra",
    },
    {
      title: "Arány kalkulátor",
      url: "kalkulatorok/arany-kalkulator.html",
      category: "mindennapi",
      description: "Számold ki egy rész arányát az egészhez képest.",
      keywords: "arány rész egész százalék",
    },
    {
      title: "Üzemanyag költség kalkulátor",
      url: "kalkulatorok/uzemanyag-koltseg-kalkulator.html",
      category: "auto",
      description: "Számold ki egy út várható üzemanyagköltségét.",
      keywords: "üzemanyag benzin dízel útiköltség",
    },
    {
      title: "Autó fogyasztás kalkulátor",
      url: "kalkulatorok/auto-fogyasztas-kalkulator.html",
      category: "auto",
      description: "Számold ki a valós fogyasztást tankolás és megtett kilométer alapján.",
      keywords: "fogyasztás tankolás autó liter",
    },
    {
      title: "Hatótáv kalkulátor",
      url: "kalkulatorok/hatotav-kalkulator.html",
      category: "auto",
      description: "Becsüld meg, hány kilométert tehetsz meg a tankban lévő üzemanyaggal.",
      keywords: "hatótáv tank fogyasztás",
    },
    {
      title: "Éves autóköltség kalkulátor",
      url: "kalkulatorok/eves-auto-koltseg-kalkulator.html",
      category: "auto",
      description: "Becsüld meg az autó éves fenntartási költségét.",
      keywords: "autó fenntartás éves költség biztosítás szerviz",
    },
    {
      title: "Autó értékvesztés kalkulátor",
      url: "kalkulatorok/auto-ertekvesztes-kalkulator.html",
      category: "auto",
      description: "Számold ki, mennyit veszíthet az autó az értékéből évente.",
      keywords: "autó amortizáció értékvesztés",
    },
    {
      title: "Kilométerdíj kalkulátor",
      url: "kalkulatorok/kilometerdij-kalkulator.html",
      category: "auto",
      description: "Számold ki, mennyibe kerül egy kilométer az autóddal.",
      keywords: "kilométerdíj autó költség km",
    },
    {
      title: "CO2 kibocsátás kalkulátor",
      url: "kalkulatorok/co2-kibocsatas-kalkulator.html",
      category: "auto",
      description: "Becsüld meg az utazás szén-dioxid kibocsátását üzemanyag alapján.",
      keywords: "co2 kibocsátás autó környezet",
    },
    {
      title: "Tankolás kalkulátor",
      url: "kalkulatorok/tankolas-kalkulator.html",
      category: "auto",
      description: "Számold ki, mennyibe kerül a tankolás és mennyi liter fér bele.",
      keywords: "tankolás üzemanyag liter ár",
    },
    {
      title: "Gumiméret váltó kalkulátor",
      url: "kalkulatorok/gumi-meret-kalkulator.html",
      category: "auto",
      description: "Hasonlíts össze két gumiméretet átmérő és eltérés alapján.",
      keywords: "gumiméret váltó kerék átmérő",
    },
    {
      title: "Autópályadíj kalkulátor",
      url: "kalkulatorok/autopalyadij-kalkulator.html",
      category: "auto",
      description: "Oszd el az autópályadíjat utasok között.",
      keywords: "autópálya matrica díj utazás",
    },
    {
      title: "Utazási idő kalkulátor",
      url: "kalkulatorok/utazasi-ido-kalkulator.html",
      category: "auto",
      description: "Számold ki a várható menetidőt távolság és átlagsebesség alapján.",
      keywords: "utazási idő távolság sebesség",
    },
    {
      title: "Energia átváltó kalkulátor",
      url: "kalkulatorok/energia-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Válts át joule, kilojoule, kalória és kilowattóra között.",
      keywords: "energia joule kalória kwh átváltás",
    },
    {
      title: "Nyomás átváltó kalkulátor",
      url: "kalkulatorok/nyomas-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Válts át pascal, bar, atmoszféra és PSI között.",
      keywords: "nyomás bar psi pascal átváltás",
    },
    {
      title: "Teljesítmény átváltó kalkulátor",
      url: "kalkulatorok/teljesitmeny-atvalto-kalkulator.html",
      category: "atvaltok",
      description: "Válts át watt, kilowatt és lóerő között.",
      keywords: "teljesítmény watt kilowatt lóerő átváltás",
    },
  ];

  window.KB_DATA = {
    categories,
    calculators,
    wise: {
      url: "https://wise.prf.hn/click/camref:1100l5Km25/creativeref:1101l107482",
      image:
        "https://wise-creative.prf.hn/source/camref:1100l5Km25/creativeref:1101l107482",
    },
    adsense: {
      client: "ca-pub-2639795157074812",
      slot: "2032035454",
    },
  };
})();
